language: elixir

elixir:
  - '1.8.0'
otp_release:
  - '21.0.0'
  
sudo: false

env:
  - ELIXIR_ASSERT_TIMEOUT=2000

script:
  - mix test

before_script:  
  - kerl list installations

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

notifications:
  recipients:
    - paul@knoxen.com
